name: Publish to Nuget

on:
  release:
    types: [published]


permissions:
  contents: read
  packages: write # permission for the github token

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build JetdriveSharp/JetdriveSharp.csproj --no-restore --configuration Release
      - name: Create the package
        run: dotnet pack JetdriveSharp/JetdriveSharp.csproj --configuration Release
      - name: Publish the package to Nuget
        run: dotnet nuget push JetdriveSharp/bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json